# Compile prepare_container
FROM docker.io/ziglings/ziglang:0.12.0 AS zig
COPY container/prepare_container.zig /
RUN zig build-exe -O ReleaseSmall -mcpu=baseline -fstrip prepare_container.zig


# Compile yougram
FROM docker.io/library/golang:1.24-alpine AS go
RUN apk add --no-cache git ca-certificates just gcc g++ musl-dev

# Make templ/sqlc nop bins so the Makefile works
RUN echo -e "#!/bin/sh\nexec true" > /bin/templ
RUN echo -e "#!/bin/sh\nexec true" > /bin/sqlc
RUN chmod +x /bin/templ /bin/sqlc

WORKDIR /build
COPY src /build/src/
COPY justfile /build/
RUN just release


# Actual container
FROM scratch

EXPOSE 8000
EXPOSE 8001
VOLUME [ "/data" ]
ENTRYPOINT [ "/yougram", "serve", "--private-listen-addr", "8000", "--guest-listen-addr", "8001" ]

COPY --from=zig /prepare_container /
RUN [ "/prepare_container" ]
WORKDIR /data

COPY --from=go /build/yougram /
