FROM scratch

EXPOSE 8000
EXPOSE 8001
VOLUME [ "/data" ]
ENTRYPOINT [ "/yougram", "serve", "--private-listen-addr", "8000", "--guest-listen-addr", "8001" ]

COPY prepare_container /
RUN [ "/prepare_container" ]
WORKDIR /data

COPY yougram /
