// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

type Album struct {
	ID               int64
	Name             string
	Url              string
	Secret           string
	SecretValidUntil int64
}

type User struct {
	ID       int64
	Username string
	Password string
	Cookie   string
}
