// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package main

import (
	"context"
)

const addUser = `-- name: AddUser :exec
INSERT INTO users ( username, password, cookie ) VALUES ( ?, ?, ? )
`

type AddUserParams struct {
	Username string
	Password string
	Cookie   string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser, arg.Username, arg.Password, arg.Cookie)
	return err
}
