/* This file was generated by ConfigHeader using the Zig Build System. */
#ifndef LIBAVUTIL_AVCONFIG_H
#define LIBAVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 1
#endif /* LIBAVUTIL_AVCONFIG_H */
