// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Album struct {
	ID                  int64
	Owner               int64
	Name                string
	UrlSlug             string
	KeyPhoto            sql.NullInt64
	Shared              int64
	ReadonlySecret      string
	ReadwriteSecret     string
	AutoassignStartDate sql.NullInt64
	AutoassignEndDate   sql.NullInt64
	AutoassignLatitude  sql.NullFloat64
	AutoassignLongitude sql.NullFloat64
	AutoassignRadius    sql.NullFloat64
}

type AlbumKeyPhoto struct {
	ID     int64
	Sha256 []byte
}

type AlbumPhoto struct {
	AlbumID int64
	PhotoID int64
}

type Asset struct {
	Sha256           []byte
	CreatedAt        int64
	OriginalFilename string
	Type             string
	Thumbnail        []byte
	Thumbhash        []byte
	Description      sql.NullString
	DateTaken        sql.NullInt64
	Latitude         sql.NullFloat64
	Longitude        sql.NullFloat64
}

type Photo struct {
	ID           int64
	Owner        sql.NullInt64
	CreatedAt    int64
	DeleteAt     sql.NullInt64
	PrimaryAsset []byte
	DateTaken    sql.NullInt64
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
}

type PhotoAsset struct {
	PhotoID int64
	AssetID []byte
}

type PhotoPrimaryAsset struct {
	PhotoID          int64
	Sha256           []byte
	CreatedAt        int64
	OriginalFilename string
	Type             string
	Thumbnail        []byte
	Thumbhash        []byte
	Description      sql.NullString
	DateTaken        sql.NullInt64
	Latitude         sql.NullFloat64
	Longitude        sql.NullFloat64
}

type User struct {
	ID                   int64
	Username             string
	Password             string
	NeedsToResetPassword int64
	Cookie               string
}
