// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Album struct {
	ID                  int64
	Owner               int64
	Name                string
	UrlSlug             string
	KeyPhoto            sql.NullInt64
	Shared              int64
	ReadonlySecret      string
	ReadwriteSecret     string
	GuestPassword       sql.NullString
	DeleteAt            sql.NullInt64
	AutoassignStartDate sql.NullInt64
	AutoassignEndDate   sql.NullInt64
	AutoassignLatitude  sql.NullFloat64
	AutoassignLongitude sql.NullFloat64
	AutoassignRadius    sql.NullFloat64
}

type AlbumKeyAsset struct {
	ID     int64
	Sha256 []byte
}

type AlbumPhoto struct {
	AlbumID int64
	PhotoID int64
}

type Asset struct {
	Sha256           []byte
	CreatedAt        int64
	OriginalFilename string
	Type             string
	Thumbnail        []byte
	Thumbhash        []byte
	Description      sql.NullString
	DateTaken        sql.NullInt64
	Latitude         sql.NullFloat64
	Longitude        sql.NullFloat64
}

type AssetFace struct {
	AssetID []byte
	FaceID  int64
}

type Avatar struct {
	Sha256 []byte
	Avatar []byte
}

type Config struct {
	ID                               int64
	LastAssetAddedTime               sql.NullInt64
	LastFacialRecognitionClusterTime sql.NullInt64
}

type FaceEmbedding struct {
	ID        int64
	Embedding interface{}
	Generator int64
}

type Person struct {
	ID   int64
	Name string
}

type PersonFace struct {
	PersonID int64
	FaceID   int64
}

type Photo struct {
	ID           int64
	Owner        sql.NullInt64
	CreatedAt    int64
	DeleteAt     sql.NullInt64
	PrimaryAsset []byte
}

type PhotoAsset struct {
	PhotoID int64
	AssetID []byte
}

type PhotoFace struct {
	FaceID  int64
	PhotoID int64
}

type PhotoPrimaryAsset struct {
	PhotoID          int64
	Sha256           []byte
	CreatedAt        int64
	OriginalFilename string
	Type             string
	Thumbnail        []byte
	Thumbhash        []byte
	Description      sql.NullString
	DateTaken        sql.NullInt64
	Latitude         sql.NullFloat64
	Longitude        sql.NullFloat64
}

type User struct {
	ID                   int64
	Username             string
	Password             string
	NeedsToResetPassword int64
	Enabled              int64
	Cookie               []byte
	Avatar               []byte
}

type ValidAssetType struct {
	Type string
}
