// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addAssetToPhoto = `-- name: AddAssetToPhoto :exec
INSERT INTO photo_asset ( photo_id, asset_id ) VALUES ( ?, ? )
`

type AddAssetToPhotoParams struct {
	PhotoID int64
	AssetID []byte
}

func (q *Queries) AddAssetToPhoto(ctx context.Context, arg AddAssetToPhotoParams) error {
	_, err := q.db.ExecContext(ctx, addAssetToPhoto, arg.PhotoID, arg.AssetID)
	return err
}

const addPhotoToAlbum = `-- name: AddPhotoToAlbum :exec
INSERT OR IGNORE INTO album_photo ( album_id, photo_id ) VALUES ( ?, ? )
`

type AddPhotoToAlbumParams struct {
	AlbumID int64
	PhotoID int64
}

func (q *Queries) AddPhotoToAlbum(ctx context.Context, arg AddPhotoToAlbumParams) error {
	_, err := q.db.ExecContext(ctx, addPhotoToAlbum, arg.AlbumID, arg.PhotoID)
	return err
}

const areThereAnyUsers = `-- name: AreThereAnyUsers :one
SELECT EXISTS( SELECT 1 FROM user LIMIT 1 )
`

func (q *Queries) AreThereAnyUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, areThereAnyUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const assetExists = `-- name: AssetExists :one

SELECT EXISTS( SELECT 1 FROM asset WHERE sha256 = ? )
`

// ----------
// ASSETS --
// ----------
func (q *Queries) AssetExists(ctx context.Context, sha256 []byte) (int64, error) {
	row := q.db.QueryRowContext(ctx, assetExists, sha256)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const changePassword = `-- name: ChangePassword :exec
UPDATE user SET password = ?, cookie = ? WHERE username = ?
`

type ChangePasswordParams struct {
	Password string
	Cookie   []byte
	Username string
}

func (q *Queries) ChangePassword(ctx context.Context, arg ChangePasswordParams) error {
	_, err := q.db.ExecContext(ctx, changePassword, arg.Password, arg.Cookie, arg.Username)
	return err
}

const createAlbum = `-- name: CreateAlbum :exec

INSERT INTO album (
	owner, name, url_slug,
	shared, readonly_secret, readwrite_secret,
	autoassign_start_date, autoassign_end_date, autoassign_latitude, autoassign_longitude, autoassign_radius
) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
`

type CreateAlbumParams struct {
	Owner               int64
	Name                string
	UrlSlug             string
	Shared              int64
	ReadonlySecret      string
	ReadwriteSecret     string
	AutoassignStartDate sql.NullInt64
	AutoassignEndDate   sql.NullInt64
	AutoassignLatitude  sql.NullFloat64
	AutoassignLongitude sql.NullFloat64
	AutoassignRadius    sql.NullFloat64
}

// ----------
// ALBUMS --
// ----------
func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) error {
	_, err := q.db.ExecContext(ctx, createAlbum,
		arg.Owner,
		arg.Name,
		arg.UrlSlug,
		arg.Shared,
		arg.ReadonlySecret,
		arg.ReadwriteSecret,
		arg.AutoassignStartDate,
		arg.AutoassignEndDate,
		arg.AutoassignLatitude,
		arg.AutoassignLongitude,
		arg.AutoassignRadius,
	)
	return err
}

const createAsset = `-- name: CreateAsset :exec
INSERT OR IGNORE INTO asset (
	sha256, created_at, original_filename, type,
	thumbnail, thumbhash,
	description, date_taken, latitude, longitude )
VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
`

type CreateAssetParams struct {
	Sha256           []byte
	CreatedAt        int64
	OriginalFilename string
	Type             string
	Thumbnail        []byte
	Thumbhash        []byte
	Description      sql.NullString
	DateTaken        sql.NullInt64
	Latitude         sql.NullFloat64
	Longitude        sql.NullFloat64
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) error {
	_, err := q.db.ExecContext(ctx, createAsset,
		arg.Sha256,
		arg.CreatedAt,
		arg.OriginalFilename,
		arg.Type,
		arg.Thumbnail,
		arg.Thumbhash,
		arg.Description,
		arg.DateTaken,
		arg.Latitude,
		arg.Longitude,
	)
	return err
}

const createPhoto = `-- name: CreatePhoto :one

INSERT INTO photo ( owner, created_at, primary_asset )
VALUES( ?, ?, ? )
RETURNING id
`

type CreatePhotoParams struct {
	Owner        sql.NullInt64
	CreatedAt    int64
	PrimaryAsset []byte
}

// ----------
// PHOTOS --
// ----------
func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPhoto, arg.Owner, arg.CreatedAt, arg.PrimaryAsset)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO user ( username, password, needs_to_reset_password, cookie ) VALUES ( ?, ?, 1, ? )
RETURNING id
`

type CreateUserParams struct {
	Username string
	Password string
	Cookie   []byte
}

// ---------
// USERS --
// ---------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.Cookie)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const disableUser = `-- name: DisableUser :exec
UPDATE user SET enabled = 0 WHERE username = ?
`

func (q *Queries) DisableUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, disableUser, username)
	return err
}

const enableUser = `-- name: EnableUser :exec
UPDATE user SET enabled = 1 WHERE username = ?
`

func (q *Queries) EnableUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, enableUser, username)
	return err
}

const getAlbumAssets = `-- name: GetAlbumAssets :many
SELECT asset.sha256 AS asset, asset.type FROM asset
INNER JOIN photo_asset ON asset.sha256 = photo_asset.asset_id
INNER JOIN photo ON photo.id = photo_asset.photo_id
INNER JOIN album_photo ON photo.id = album_photo.photo_id
INNER JOIN album ON album.id = album_photo.album_id
WHERE album.id = ? AND (
	( ? OR photo.primary_asset = asset.sha256 ) -- primary assets only
	OR ( ? OR asset.type = "raw" ) -- primary assets + raws
)
`

type GetAlbumAssetsParams struct {
	ID      int64
	Column2 interface{}
	Column3 interface{}
}

type GetAlbumAssetsRow struct {
	Asset []byte
	Type  string
}

func (q *Queries) GetAlbumAssets(ctx context.Context, arg GetAlbumAssetsParams) ([]GetAlbumAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumAssets, arg.ID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumAssetsRow
	for rows.Next() {
		var i GetAlbumAssetsRow
		if err := rows.Scan(&i.Asset, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumAutoassignRules = `-- name: GetAlbumAutoassignRules :many
SELECT
	id AS album_id,
	autoassign_start_date AS start_date,
	autoassign_end_date AS end_date,
	autoassign_latitude AS latitude,
	autoassign_longitude AS longitude,
	autoassign_radius AS radius
FROM album WHERE ? BETWEEN autoassign_start_date AND autoassign_end_date
`

type GetAlbumAutoassignRulesRow struct {
	AlbumID   int64
	StartDate sql.NullInt64
	EndDate   sql.NullInt64
	Latitude  sql.NullFloat64
	Longitude sql.NullFloat64
	Radius    sql.NullFloat64
}

func (q *Queries) GetAlbumAutoassignRules(ctx context.Context) ([]GetAlbumAutoassignRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumAutoassignRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumAutoassignRulesRow
	for rows.Next() {
		var i GetAlbumAutoassignRulesRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.StartDate,
			&i.EndDate,
			&i.Latitude,
			&i.Longitude,
			&i.Radius,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumByURL = `-- name: GetAlbumByURL :one
SELECT album.id, owner, url_slug, user.username AS owner_username, album.name, shared, readonly_secret, readwrite_secret, album_key_asset.sha256 AS key_photo_sha256
FROM album
LEFT OUTER JOIN album_key_asset ON album.id = album_key_asset.id
INNER JOIN user ON album.owner = user.id
WHERE url_slug = ?
`

type GetAlbumByURLRow struct {
	ID              int64
	Owner           int64
	UrlSlug         string
	OwnerUsername   string
	Name            string
	Shared          int64
	ReadonlySecret  string
	ReadwriteSecret string
	KeyPhotoSha256  []byte
}

func (q *Queries) GetAlbumByURL(ctx context.Context, urlSlug string) (GetAlbumByURLRow, error) {
	row := q.db.QueryRowContext(ctx, getAlbumByURL, urlSlug)
	var i GetAlbumByURLRow
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.UrlSlug,
		&i.OwnerUsername,
		&i.Name,
		&i.Shared,
		&i.ReadonlySecret,
		&i.ReadwriteSecret,
		&i.KeyPhotoSha256,
	)
	return i, err
}

const getAlbumOwner = `-- name: GetAlbumOwner :one
SELECT owner FROM album WHERE id = ?
`

func (q *Queries) GetAlbumOwner(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAlbumOwner, id)
	var owner int64
	err := row.Scan(&owner)
	return owner, err
}

const getAlbumPhotos = `-- name: GetAlbumPhotos :many
SELECT photo.id, photo_primary_asset.sha256, photo_primary_asset.thumbhash
FROM photo
INNER JOIN album_photo ON album_photo.photo_id = photo.id
INNER JOIN photo_primary_asset ON photo.id = photo_primary_asset.photo_id
WHERE album_photo.album_id = ? AND album_photo.photo_id = photo.id
ORDER BY photo_primary_asset.date_taken ASC
`

type GetAlbumPhotosRow struct {
	ID        int64
	Sha256    []byte
	Thumbhash []byte
}

func (q *Queries) GetAlbumPhotos(ctx context.Context, albumID int64) ([]GetAlbumPhotosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumPhotos, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumPhotosRow
	for rows.Next() {
		var i GetAlbumPhotosRow
		if err := rows.Scan(&i.ID, &i.Sha256, &i.Thumbhash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumsForUser = `-- name: GetAlbumsForUser :many
SELECT album.name, album.url_slug, album_key_asset.sha256 AS key_photo_sha256 FROM album
LEFT OUTER JOIN album_key_asset ON album.id = album_key_asset.id
WHERE ( album.shared OR album.owner = ? )
ORDER BY album.name
`

type GetAlbumsForUserRow struct {
	Name           string
	UrlSlug        string
	KeyPhotoSha256 []byte
}

func (q *Queries) GetAlbumsForUser(ctx context.Context, owner int64) ([]GetAlbumsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getAlbumsForUser, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumsForUserRow
	for rows.Next() {
		var i GetAlbumsForUserRow
		if err := rows.Scan(&i.Name, &i.UrlSlug, &i.KeyPhotoSha256); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetGuestMetadata = `-- name: GetAssetGuestMetadata :one
SELECT type, original_filename, EXISTS(
	SELECT 1 FROM photo_asset
	INNER JOIN photo ON photo.id = photo_asset.photo_id
	INNER JOIN album_photo ON album_photo.photo_id = photo.id
	INNER JOIN album ON album.id = album_photo.album_id
	WHERE album.url_slug = ? AND ( album.readonly_secret = ? OR album.readwrite_secret = ? )
) AS has_permission
FROM asset WHERE sha256 = ?
`

type GetAssetGuestMetadataParams struct {
	UrlSlug         string
	ReadonlySecret  string
	ReadwriteSecret string
	Sha256          []byte
}

type GetAssetGuestMetadataRow struct {
	Type             string
	OriginalFilename string
	HasPermission    int64
}

func (q *Queries) GetAssetGuestMetadata(ctx context.Context, arg GetAssetGuestMetadataParams) (GetAssetGuestMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetGuestMetadata,
		arg.UrlSlug,
		arg.ReadonlySecret,
		arg.ReadwriteSecret,
		arg.Sha256,
	)
	var i GetAssetGuestMetadataRow
	err := row.Scan(&i.Type, &i.OriginalFilename, &i.HasPermission)
	return i, err
}

const getAssetGuestThumbnail = `-- name: GetAssetGuestThumbnail :one
SELECT thumbnail, original_filename, EXISTS(
	SELECT 1 FROM photo_asset
	INNER JOIN photo ON photo.id = photo_asset.photo_id
	INNER JOIN album_photo ON album_photo.photo_id = photo.id
	INNER JOIN album ON album.id = album_photo.album_id
	WHERE album.url_slug = ? AND ( album.readonly_secret = ? OR album.readwrite_secret = ? )
) AS has_permission
FROM asset WHERE sha256 = ?
`

type GetAssetGuestThumbnailParams struct {
	UrlSlug         string
	ReadonlySecret  string
	ReadwriteSecret string
	Sha256          []byte
}

type GetAssetGuestThumbnailRow struct {
	Thumbnail        []byte
	OriginalFilename string
	HasPermission    int64
}

func (q *Queries) GetAssetGuestThumbnail(ctx context.Context, arg GetAssetGuestThumbnailParams) (GetAssetGuestThumbnailRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetGuestThumbnail,
		arg.UrlSlug,
		arg.ReadonlySecret,
		arg.ReadwriteSecret,
		arg.Sha256,
	)
	var i GetAssetGuestThumbnailRow
	err := row.Scan(&i.Thumbnail, &i.OriginalFilename, &i.HasPermission)
	return i, err
}

const getAssetMetadata = `-- name: GetAssetMetadata :one
SELECT type, original_filename, EXISTS(
	SELECT 1 FROM photo_asset
	INNER JOIN photo ON photo.id = photo_asset.photo_id
	INNER JOIN album_photo ON album_photo.photo_id = photo.id
	INNER JOIN album ON album.id = album_photo.album_id
	WHERE photo_asset.asset_id = ? AND ( photo.owner = ? OR album.owner = ? OR album.shared )
) AS has_permission
FROM asset WHERE sha256 = ?
`

type GetAssetMetadataParams struct {
	AssetID []byte
	Owner   sql.NullInt64
	Owner_2 int64
	Sha256  []byte
}

type GetAssetMetadataRow struct {
	Type             string
	OriginalFilename string
	HasPermission    int64
}

func (q *Queries) GetAssetMetadata(ctx context.Context, arg GetAssetMetadataParams) (GetAssetMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetMetadata,
		arg.AssetID,
		arg.Owner,
		arg.Owner_2,
		arg.Sha256,
	)
	var i GetAssetMetadataRow
	err := row.Scan(&i.Type, &i.OriginalFilename, &i.HasPermission)
	return i, err
}

const getAssetPhotos = `-- name: GetAssetPhotos :many
SELECT photo.id FROM photo, photo_asset
WHERE photo_asset.asset_id = ? AND photo.owner = ? AND photo.id = photo_asset.photo_id
`

type GetAssetPhotosParams struct {
	AssetID []byte
	Owner   sql.NullInt64
}

func (q *Queries) GetAssetPhotos(ctx context.Context, arg GetAssetPhotosParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAssetPhotos, arg.AssetID, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssetThumbnail = `-- name: GetAssetThumbnail :one
SELECT thumbnail, original_filename FROM asset WHERE sha256 = ?
`

type GetAssetThumbnailRow struct {
	Thumbnail        []byte
	OriginalFilename string
}

func (q *Queries) GetAssetThumbnail(ctx context.Context, sha256 []byte) (GetAssetThumbnailRow, error) {
	row := q.db.QueryRowContext(ctx, getAssetThumbnail, sha256)
	var i GetAssetThumbnailRow
	err := row.Scan(&i.Thumbnail, &i.OriginalFilename)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT asset.sha256, asset.type, asset.original_filename FROM photo, asset
WHERE photo.id = ? AND asset.sha256 = IFNULL( photo.primary_asset,
	( SELECT sha256 FROM asset
	INNER JOIN photo_asset ON photo_asset.asset_id = asset.sha256
	WHERE photo_asset.photo_id = photo.id AND asset.type != "raw"
	ORDER BY asset.created_at DESC LIMIT 1 ) )
`

type GetPhotoRow struct {
	Sha256           []byte
	Type             string
	OriginalFilename string
}

func (q *Queries) GetPhoto(ctx context.Context, id int64) (GetPhotoRow, error) {
	row := q.db.QueryRowContext(ctx, getPhoto, id)
	var i GetPhotoRow
	err := row.Scan(&i.Sha256, &i.Type, &i.OriginalFilename)
	return i, err
}

const getPhotoAssets = `-- name: GetPhotoAssets :many
SELECT asset.sha256 AS asset, asset.type, photo.owner = ? AS owned
FROM asset
INNER JOIN photo_asset ON asset.sha256 = photo_asset.asset_id
INNER JOIN photo ON photo.id = photo_asset.photo_id
WHERE photo.id = ? AND (
	( ? OR photo.primary_asset = asset.sha256 ) -- primary assets only
	OR ( ? OR asset.type = "raw" ) -- primary assets + raws
)
`

type GetPhotoAssetsParams struct {
	Owner   sql.NullInt64
	ID      int64
	Column3 interface{}
	Column4 interface{}
}

type GetPhotoAssetsRow struct {
	Asset []byte
	Type  string
	Owned bool
}

func (q *Queries) GetPhotoAssets(ctx context.Context, arg GetPhotoAssetsParams) ([]GetPhotoAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPhotoAssets,
		arg.Owner,
		arg.ID,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPhotoAssetsRow
	for rows.Next() {
		var i GetPhotoAssetsRow
		if err := rows.Scan(&i.Asset, &i.Type, &i.Owned); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhotoOwner = `-- name: GetPhotoOwner :one
SELECT owner FROM photo WHERE id = ?
`

func (q *Queries) GetPhotoOwner(ctx context.Context, id int64) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getPhotoOwner, id)
	var owner sql.NullInt64
	err := row.Scan(&owner)
	return owner, err
}

const getUserAuthDetails = `-- name: GetUserAuthDetails :one
SELECT id, password, needs_to_reset_password, enabled, cookie FROM user WHERE username = ?
`

type GetUserAuthDetailsRow struct {
	ID                   int64
	Password             string
	NeedsToResetPassword int64
	Enabled              int64
	Cookie               []byte
}

func (q *Queries) GetUserAuthDetails(ctx context.Context, username string) (GetUserAuthDetailsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAuthDetails, username)
	var i GetUserAuthDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Password,
		&i.NeedsToResetPassword,
		&i.Enabled,
		&i.Cookie,
	)
	return i, err
}

const getUserPhotos = `-- name: GetUserPhotos :many
SELECT photo.id, photo_primary_asset.sha256, photo_primary_asset.thumbhash
FROM photo
INNER JOIN photo_primary_asset ON photo.id = photo_primary_asset.photo_id
WHERE owner = ? ORDER BY photo_primary_asset.date_taken DESC
`

type GetUserPhotosRow struct {
	ID        int64
	Sha256    []byte
	Thumbhash []byte
}

func (q *Queries) GetUserPhotos(ctx context.Context, owner sql.NullInt64) ([]GetUserPhotosRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserPhotos, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPhotosRow
	for rows.Next() {
		var i GetUserPhotosRow
		if err := rows.Scan(&i.ID, &i.Sha256, &i.Thumbhash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT username FROM user WHERE enabled = 1
`

func (q *Queries) GetUsers(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var username string
		if err := rows.Scan(&username); err != nil {
			return nil, err
		}
		items = append(items, username)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPassword = `-- name: ResetPassword :exec
UPDATE user SET password = ?, needs_to_reset_password = 1, cookie = ? WHERE username = ?
`

type ResetPasswordParams struct {
	Password string
	Cookie   []byte
	Username string
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, resetPassword, arg.Password, arg.Cookie, arg.Username)
	return err
}

const setAlbumIsShared = `-- name: SetAlbumIsShared :exec
UPDATE album SET shared = ? WHERE id = ? AND owner = ?
`

type SetAlbumIsSharedParams struct {
	Shared int64
	ID     int64
	Owner  int64
}

func (q *Queries) SetAlbumIsShared(ctx context.Context, arg SetAlbumIsSharedParams) error {
	_, err := q.db.ExecContext(ctx, setAlbumIsShared, arg.Shared, arg.ID, arg.Owner)
	return err
}

const setAlbumSettings = `-- name: SetAlbumSettings :exec
UPDATE album SET name = ?, url_slug = ? WHERE id = ? AND owner = ?
`

type SetAlbumSettingsParams struct {
	Name    string
	UrlSlug string
	ID      int64
	Owner   int64
}

func (q *Queries) SetAlbumSettings(ctx context.Context, arg SetAlbumSettingsParams) error {
	_, err := q.db.ExecContext(ctx, setAlbumSettings,
		arg.Name,
		arg.UrlSlug,
		arg.ID,
		arg.Owner,
	)
	return err
}
